apiVersion: v1
kind: Secret
metadata:
  name: secret-salaka
  namespace: development
type: Opaque
data:
  DATABASE_USERNAME: YWxlc2hh
  DATABASE_PASSWORD: YWxlc2hhMjAyMQ==
  DATABASE_DATABASE: c2FrYWxh
  DATABASE_HOST: MTkyLjE2OC4wLjE4Nw==
  DATABASE_PORT: MzMwNg==
